name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Git LFS
        run: git lfs install

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cats-and-dogs-api"
          heroku_email: "hello.boriskas@gmail.com"
          usedocker: false

      - name: Deploy to Heroku
        run: |
          git add . -f
          git commit -m "Deploy"
          git push heroku main
